[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # Mold linker
    # - Arch: `sudo pacman -S mold clang`
    "-Clink-arg=-fuse-ld=mold",

    # # Nightly
    # "-Zshare-generics=y",
    # actually seeing a slight slowdown when using this
    # "-Zthreads=0",
]

[target.x86_64-pc-windows-msvc]
# LLD linker
#
# You may need to install it:
#
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools
# ```
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
    # Nightly
    # "-Zshare-generics=n", # This needs to be off if you use dynamic linking on Windows.
    # "-Zthreads=0",
]

# Uncommenting the following improves compile times, but reduces the amount of debug info to 'line number tables only'
# improves full compilation by about 10 s on 5900x
# [profile.dev]
# debug = 1
